### ISSUE TITLE
Demo link doesn't work 

### ISSUE THREAD

**Issue by cameronking4** [sineverba/body-measurement-frontend#116]
Tried to test demo but shows blank page. Checked sources and I don't see any network call. Would love to test this project and possibly fund more development.

**Comment by cameronking4** [comment]
![image](https://user-images.githubusercontent.com/35708477/143134824-2b51e8e1-75d4-4b1a-b229-6bd6376a0107.png)

**Comment by cameronking4** [comment]
Is there a demo login credentials I could use?

**Comment by sineverba** [comment]
Hey!
Thank you for reaching me.

This is a custom and personal project, so, there isn't any demo credentials. You need to clone Backend and create your own credentials (it is a Laravel project).

For the Frontend, if you see the network tab, there are some network calls. E.g.: the backend version in the footer.

To open modal login, you need to click on "Login". So, definitively, it isn't really a blank page. ;)

**Comment by cameronking4** [comment]
Having hard time getting backend to run. I just want to confirm if this project will generate body measurements for me from image? Want to make sure before I try to figure out how create credentials

**Comment by sineverba** [comment]
No, this project doesn't generate body measurements from image. You need a backend (in which language you want) and insert hand by hand the values.
